### ISSUE TITLE
Landing page image/hero

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Chinese#4]
Hero image just needs to be sized and placed, please and thank you.

**Comment by LabLayers** [comment]
Hero image: http://develop.cla.temple.edu/arabic/media/iStock_Arabic%20Nabawi%20Mosque.jpg

**Comment by pixelyunicorn** [comment]
Hero image: http://develop.cla.temple.edu/chinese/media/boat.jpg

What should the header text for the hero be?

**Comment by ZMcGroarty** [comment]
![hero_chinese-min](https://cloud.githubusercontent.com/assets/15017242/23415399/120d9f9e-fdad-11e6-9954-8d7f29df3773.png)

**Comment by CVE82** [comment]
LOVE!
